log4r_config:
  # define all loggers ...
  loggers:
    - name      : test
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile

  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "log"
    file: "my_log" # this will be overrided by lumber config.
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter